[package]
name = "image-transfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.0"
eframe = "0.22.0"
egui_file = "0.9.0"
futures = "0.3.28"
image = "0.24.6"
rfd = "0.11.4"
